name: NPM CI
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm test
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') && (github.event_name == 'push')
    permissions: 
      contents: read
      packages: write 
    steps:
      - run: \[ $(git describe --tags --exact-match) = $(npm -s run env echo '$npm_package_version') \]
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
